name = "pmtiles-cloudflare"
main = "src/index.ts"
compatibility_date = "2022-10-18"
minify = true

# Replace the bucket names with your own
r2_buckets  = [
  { binding = "BUCKET", preview_bucket_name = "my-bucket-development", bucket_name = "my-bucket-production" }
]