name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: cd js && npm install && npm run build
      - run: echo "VITE_GIT_SHA=$(git rev-parse --short HEAD)" >> app/.env
      - run: cd app && npm install && ./node_modules/.bin/tsc && ./node_modules/.bin/vite build --base=/PMTiles/
      - run: cd serverless/aws && python create_lambda_function.py && cp lambda_function.zip ../../app/dist
      - run: cd serverless/cloudflare && npm install && npm run build && cp dist/index.js ../../app/dist
      - name: build_app
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          force_orphan: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: cd js && npm install && npm test
      - run: cd python && python -m unittest test/test_*
      - run: cd cpp && make
      - run: cd serverless/aws && python -m unittest test_*.py
      - run: cd serverless/cloudflare && npm install && npm test
